spring:
  application:
    name: config-server
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/timeLessmeng/SpringcloudConfig/
          search-paths: respo
          username:
          password:
server:
  port: 8444
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8222/eureka/
