spring:
  application:
    name: config-server
  cloud:
      config:
        label: master
        server:
          git:
            uri: https://github.com/forezp/SpringcloudConfig/
            searchPaths: respo
            username:
            password:
server:
  port: 8443